### ISSUE TITLE
Couldn't pass ProxyInitializeEvent to cleanscreenshare 2.6.0

### ISSUE THREAD

**Issue by Crazed981** [frafol/CleanScreenShare#14]
```
[04:05:07] [Velocity Async Event Executor - #0/ERROR] [com.velocitypowered.proxy.event.VelocityEventManager]: Couldn't pass ProxyInitializeEvent to cleanscreenshare 2.6.0
java.lang.NoClassDefFoundError: com/alessiodp/libby/VelocityLibraryManager
	at it.frafol.cleanss.velocity.CleanSS.loadLibraries(CleanSS.java:302) ~[?:?]
	at it.frafol.cleanss.velocity.CleanSS.onProxyInitialization(CleanSS.java:111) ~[?:?]
	at it.frafol.cleanss.velocity.Lmbda$15.execute(Unknown Source) ~[?:?]
	at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:56) ~[velocity-3.3.0-SNAPSHOT-415.jar:3.3.0-SNAPSHOT (git-00ed2284-b415)]
	at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:598) ~[velocity-3.3.0-SNAPSHOT-415.jar:3.3.0-SNAPSHOT (git-00ed2284-b415)]
	at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:479) ~[velocity-3.3.0-SNAPSHOT-415.jar:3.3.0-SNAPSHOT (git-00ed2284-b415)]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.lang.ClassNotFoundException: com.alessiodp.libby.VelocityLibraryManager
	at com.velocitypowered.proxy.plugin.PluginClassLoader.loadClass0(PluginClassLoader.java:87) ~[velocity-3.3.0-SNAPSHOT-415.jar:3.3.0-SNAPSHOT (git-00ed2284-b415)]
	at com.velocitypowered.proxy.plugin.PluginClassLoader.loadClass(PluginClassLoader.java:64) ~[velocity-3.3.0-SNAPSHOT-415.jar:3.3.0-SNAPSHOT (git-00ed2284-b415)]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
	... 9 more
[04:05:07] [Velocity Async Event Executor - #0/WARN] [com.velocitypowered.proxy.network.ConnectionManager]: The server channel initializer has been replaced by java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[04:05:07] [Velocity Async Event Executor - #0/WARN] [com.velocitypowered.proxy.network.ConnectionManager]: The backend channel initializer has been replaced by java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
```

**Comment by frafol** [comment]
can you try downloading from https://objects.githubusercontent.com/github-production-release-asset-2e65be/570967905/c3fadd84-2555-4481-bb5e-4033ee240fc0?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=releaseassetproduction%2F20240812%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20240812T084438Z&X-Amz-Expires=300&X-Amz-Signature=527724e02bffed8a6da3cdf373a8b2618481c62ab38465c2baa2c7d24a3eac1e&X-Amz-SignedHeaders=host&actor_id=0&key_id=0&repo_id=570967905&response-content-disposition=attachment%3B%20filename%3Dcleanscreenshare-2.6.0.jar&response-content-type=application%2Foctet-stream

**Comment by Crazed981** [comment]
link doesn't work

**Comment by frafol** [comment]
fixed in https://github.com/frafol/CleanScreenShare/releases/download/release/cleanscreenshare-2.6.0.jar
